# Site settings
title: CELELAS
email: jakeli@live.cn
description: > # this means to ignore newlines until "baseurl:"
  Blogs and technical notes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "sirlis.github.io" # the base hostname & protocol for your site
permalink: :year-:month-:day-:title/ #永久链接格式

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
# twitter:  username
# weibo:    ID
github:   sirlis
# codepen:  username
# dribbble: username


# Comment
disqus_shortname: disqus_agXkcuCp1k


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
